added images
CFC-Servers/cfc_attention_monitoring pull request #2
Opened 2021-11-20 23:23 UTC by code-Toby

2021-11-20 23:24 UTC, wrefgtzweve commented
Looks good

2021-11-22 04:23 UTC, plally requested changes

2021-11-22 04:23 UTC, plally commented on README.md
> + This addon display's a icon above the head of player's that are currently tabbed out of the game.
```suggestion
 This addon displays a icon above the head of players that are currently tabbed out of the game.
```

2021-11-22 04:24 UTC, plally commented on README.md
> +  It send's the player that tabbed out to the server to be put in a table of tabbed out player's.
```suggestion
  It sends the player that tabbed out to the server to be put in a table of tabbed out players.
```

2021-11-22 04:25 UTC, plally commented on README.md
> +  icon's.
```suggestion
  icons.
```

2021-11-26 18:53 UTC, merged